version: '3.3'
services:
  mySql:
    image: mysql:8.4.4
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'p@ssword'
      MYSQL_ROOT_PASSWORD: 'p@ssword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
