my:
  name: local

#Determines the timeout in milliseconds until a connection is established.
app:
  template:
    request-timeout: 60000
    connect-timeout: 60000
    socket-timeout: 60000
    max-request-connection: 1000
    max-request-connection-per-route: 200

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging:
  level:
    com:
      example: TRACE
    org:
      springframework: ERROR
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} | %-5level | %X{CORRELATION_ID} | %c{1} | %msg%n"

springdoc:
  server:
    url: http://localhost:8080
  api-docs:
    enabled: true
    path: /api-doc
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    groups-order: asc

spring:
  application:
    name: demo
  jackson:
    time-zone: "Asia/Bangkok"
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: p@ssword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
